all: what-is-wsgi.html testing-wsgi-apps-with-twill.html

what-is-wsgi.html: what-is-wsgi.rst
	rst2html.py what-is-wsgi.rst what-is-wsgi.html

testing-wsgi-apps-with-twill.html: testing-wsgi-apps-with-twill.rst
	rst2html.py testing-wsgi-apps-with-twill.rst testing-wsgi-apps-with-twill.html
